### PR TITLE
#26 if Vaadin 8 plugin is also present, register the extension under …

### LINKED ISSUE #26: Conflict with Vaadin 8 plugin
When both `com.devsoap.plugin.vaadin` and `com.vaadin` plugins are used in the same project (usually the MPR), they both publish `vaadin{}` Gradle configuration extension which conflicts and will make Gradle fail with an exception. The simplest solution is to rename the extension of `com.vaadin` to something else. Options:

1. Make `com.vaadin` to rename the extension to something else only when `com.devsoap.plugin.vaadin` is discovered? OR
2. Rename the `com.vaadin` extension permanently to something else.

Possible new names:
1. `vaadin10`
2. `vaadin14`
3. `vaadinFlow`
4. Possibly others?

@mstahv what is your opinion please?

### PR DESCRIPTION
**Pull request by mvysny**
…the name of vaadinFlow. Closes #26

The current solution is that the plugin will temporarily use the `vaadinFlow{}` config block instead of `vaadin{}` iff Vaadin 8 plugin is also applied.

### CODE REVIEW

File: src/main/groovy/com/vaadin/gradle/VaadinPlugin.groovy [hunk 1]
```diff
@@ -109,7 +109,12 @@ class VaadinPlugin implements Plugin<Project> {
                     create(VaadinClientDependenciesExtension.NAME, VaadinClientDependenciesExtension, project)
                 } else {
                     // need to use reflection since Groovy+Kotlin projects are not really supported.
-                    create('vaadin', Class.forName("com.vaadin.gradle.VaadinFlowPluginExtension"), project)
+                    def extensionName = 'vaadin'
+                    if (findByName(extensionName) != null) {
+                        // fixes https://github.com/vaadin/vaadin-gradle-plugin/issues/26
+                        extensionName = 'vaadinFlow'
```
Comment (mstahv) [inline src/main/groovy/com/vaadin/gradle/VaadinPlugin.groovy]: I think this is the only way to do it, chatted with Lois from Gradle team. But let's use different name, lets use vaadin14 if there is a collision.
